### ISSUE TITLE
Bring back caching on Github Actions

### ISSUE THREAD

**Issue by rvlb** [vintasoftware/entity-embed#28]
I has been removed here https://github.com/vintasoftware/entity-embed/pull/27 because of errors when running `pip install` following a suggestion here https://github.com/pypa/pip/issues/9880#issuecomment-827807619.

Creating this to track the issue and bring caching back once Github Actions behavior is fixed.

**Comment by fjsj** [comment]
@rvlb this may be the solution: https://github.com/pypa/pip/issues/9880#issuecomment-831012160
