### ISSUE TITLE
Implement LinkageEmbed fit with cpu in Record Linkage example

### ISSUE THREAD

**Issue by hanyangunivleejoohyun** [vintasoftware/entity-embed#31]
Hi

I having problem with key base blocking, so I'm trying new blocking with this repository.
(First, I really appreciate about this open source! :) )

When I tried [LinkageEmbed](https://github.com/vintasoftware/entity-embed/blob/963797c72bb0be2caefa90468d7ca8880332fa42/entity_embed/entity_embed.py#L424) to train in Record Linkage example,
I got error below.
![image](https://user-images.githubusercontent.com/19625332/125271512-ce666e00-e345-11eb-9b52-cbb1e9e9a8b0.png)

I found it caused from pytorch GPU setting.
But, In my environment I can't use GPU so I want to implement it with only CPU.

So, what I want to know is how I can manipulate GPU or CPU options with LinkageEmbed Object.
```
# That's what I implemted code :(
trainer = model.fit(
    datamodule,
    min_epochs=5,
    max_epochs=100,
    check_val_every_n_epoch=1,
    early_stop_monitor="valid_recall_at_0.3",
    tb_save_dir='tb_logs',
    tb_name='kb_song-bugs_song'
)
```
In the Readme.md, I read entity-embed can be implemented with CPU in powerful laptop.
But, I couldn't find how to do that.

it's my first time to asking in open source, so if I make some mistakes.
Please let me know. I'll fix or add something

Thank you :)

**Comment by fjsj** [comment]
Hi @hanyangunivleejoohyun, the laptop described on README has a RTX 2070 GPU. But indeed you can run Entity Embed on CPU, it will just take much longer to train/evaluate.

When calling `model.fit`, try setting `use_gpu=False`. 
LMK if this doesn't work for you. Closing this issue for now.
