### ISSUE TITLE
Not able to install on windows, possibly due to dependency on n2

### ISSUE THREAD

**Issue by peeyushsinghal** [vintasoftware/entity-embed#32]
Hello Team, I am having problems installing entity-embed on windows.
I'm using PyCharm to install entity-embed and also manually checked using "pip install entity-embed"
I'm getting the following error

"C:\Users\singhape\AppData\Local\Temp\pip-install-8s9to2zf\n2_71dd50889bc04357a46bb82908dbef3c\setup.py", line 66, in define_extensions
      raise AttributeError("Installation on Windows is not supported yet.")
  AttributeError: Installation on Windows is not supported yet.

I suspect this is due to n2 package not supported for windows? can you confirm this?

Also, please provide any alternate way possible.

thanks,
Peeyush

**Comment by fjsj** [comment]
Hi @peeyushsinghal, I never tested the project on Windows. Besides n2, I'm not sure if other packages support Windows.
I suggest using WSL 2 to run this on Windows.
Another option is to write your own training code using as basis the model code: https://github.com/vintasoftware/entity-embed/blob/main/entity_embed/models.py

Closing for now.

**Comment by peeyushsinghal** [comment]
Thank you for your response

I have now been using this package on WSL now, works like a charm.

Also, do you have any intention of including non string entities? I am
particularly interested in latitude and longitude, as they can help much in
blocking.

Appreciate if you can let me know.

Thanks

**Comment by fjsj** [comment]
@peeyushsinghal latitude and longitude can probably be easily embedded and included as a field. If you have papers that suggest how to embed latlng, please share. Also, if you have datasets that can help us test the performance of this embedding, that would be great. I think those are the main blockers for implementing this.
